### ISSUE TITLE
Test of SparseVector fails when device not completely idle

### ISSUE THREAD

**Issue by hahnjo** [apt-sim/AdePT#109]
Executing two instances of `test_sparsevector` reliably fails with `Error in compact.` as the last line.

**Comment by agheata** [comment]
> Executing two instances of `test_sparsevector` reliably fails with `Error in compact.` as the last line.

What do you mean by two instances, how do you run?

**Comment by hahnjo** [comment]
> > Executing two instances of `test_sparsevector` reliably fails with `Error in compact.` as the last line.
> 
> What do you mean by two instances, how do you run?

I open two terminals and start the executable twice so that they run at the same time.

**Comment by agheata** [comment]
I am probably not fast enough to switch (I'm a gamer though ;-) ) so cannot reproduce, maybe I can increase the vector size or start the function in 2 CPU threads...

**Comment by agheata** [comment]
Yes, I was not fast enough, so I increased the size to 1 << 24 and I can reproduce in the terminal that starts first. Quite interesting...

**Comment by hahnjo** [comment]
Could of course be related to the exact hardware and software configuration as well as load / timing. On my system, it suffices if there is some overlap for both runs to fail (I use two panes in `tmux` that I switch to and paste + execute the command)

**Comment by agheata** [comment]
Adding: `COPCORE_CUDA_CHECK(cudaDeviceSynchronize());` after the last `get_vector_data` seems to fix it for me, one has to wait for the data filled by the kernel to arrive at the host... It worked by chance just because the device was idle. Does this work also for you?

**Comment by hahnjo** [comment]
Yes, seems to work. I think we should also synchronize after the `print` kernels, just to be sure.

**Comment by hahnjo** [comment]
@agheata can you submit a fix for this?
