### ISSUE TITLE
Help following instructions to compile

### ISSUE THREAD

**Issue by shefmarkh** [apt-sim/AdePT#11]
Hello,

Using the current master, it is unclear where I need to point these two items at:

-DVecCore_DIR=<path_to_veccore_installation>/share/VecCore/cmake \
   -DVecGeom_DIR=<path_to_vecgeom_installation>/lib/cmake/VecGeom \

in the cmake command.

I downloaded VecGeom:

git clone https://gitlab.cern.ch/VecGeom/VecGeom.git

and create a build directory, in which I built and installed.

Then I can see e.g. 

ls /home/Mark_Hodgkinson_irisiam/VecGeom/build
CMakeCache.txt	CTestTestfile.cmake    Makefile  VecGeom	      VecGeomConfigVersion.cmake  buildExternals       cmake_uninstall.cmake  libvecgeom.a	  recmake_replay.sh
CMakeFiles	DartConfiguration.tcl  Testing	 VecGeomConfig.cmake  VecGeomTargets.cmake	  cmake_install.cmake  installExternals       recmake_initial.sh  test

in which I don't see anything that looks like:

 -DVecGeom_DIR=<path_to_vecgeom_installation>/lib/cmake/VecGeom

I checked subdirectories but don't find any folders with names like lib or cmake. I add similar issues with the veccore I downloaded.

Trying to just use their top directories does not work for me:

 cmake -S. -B./adept-build -DVecCore_DIR=../veccore/ -DVecGeom_DIR=../VecGeom/
CMake Error at CMakeLists.txt:43 (find_package):
  By not providing "FindVecCore.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VecCore", but
  CMake did not find one.

  Could not find a package configuration file provided by "VecCore"
  (requested version 0.5.2) with any of the following names:

    VecCoreConfig.cmake
    veccore-config.cmake

  Add the installation prefix of "VecCore" to CMAKE_PREFIX_PATH or set
  "VecCore_DIR" to a directory containing one of the above files.  If
  "VecCore" provides a separate development package or SDK, be sure it has
  been installed.

Could someone advise how to correctly install VecCore and VecGeom, and then how to use them with cmake in this project?

Cheers,

Mark

**Comment by drbenmorgan** [comment]
> and create a build directory, in which I built and installed.

What was the value of `CMAKE_INSTALL_PREFIX` when you configured/installed?  If this wasn't set it would have defaulted to `/usr/local`. If you run `make install` (in the VecGeom build directory) then it should print out some info as to where the files got installed to.

**Comment by shefmarkh** [comment]
Thanks @drbenmorgan. Yes:

cmake -S. -B./adept-build -DVecCore_DIR=/usr/local/share/VecCore/cmake/ -DVecGeom_DIR=/usr/local/lib64/cmake/VecGeom/

worked for me.

Cheers,

Mark
