### ISSUE TITLE
Roadmap for AdePT

### ISSUE THREAD

**Issue by agheata** [apt-sim/AdePT#113]
**March 2021**

Example demonstrating interfacing to G4HepEm library and tracking in constant magnetic field implemented (done for e-/e+).
- Add some gamma interactions: pair production and Compton scattering
- Transport physics tables and material couple association via persistent layer (example 7)

**April 2021**

Implement an example allowing physics validation between AdePT and Geant4 (equivalent to TestEM3 used for GeantV validation).
- Connect physics with tracking information (current logical volume)
- Add support for scoring and transport to the host

**May 2021**

Geant4 example implemented to allow calling AdePT like a fast simulation process, delegating the simulation of the whole EM shower coming from a particle entering the calorimeter volume and then transferring back the energy depositions. 

- The first round of optimization for the workflow and data structure
- If proven efficient, add support for multi-event parallelism (track buffer filled from multiple Geant4 event threads)
- Adapt workflow to support bidirectional data streams, adapt scheduling of stepping loop kernels to deal with the new conditions

**June 2021**

First version magnetic field propagator for non-constant field implemented. 

- Not on the critical path for the demonstrator, but if having it would contribute to a more realistic comparison

**September 2021**

First complete AdePT simulation running, including all EM interactions,  tracking in a non-constant magnetic field (optionally), sensitive detector functionality.

- Validation of combined Geant4 + AdePT results against Geant4 standalone on a simple + more realistic setup (CMS detector)
- What we will have here is going to be the state-of-the-art to use for validation, performance comparisons

**November 2021**

Second round of optimization and performance assessment.

- workflow/scheduling optimizations
- component optimizations (geometry navigation)
- single precision study

**January 2022** 

HSF meeting discussing the results and planning a community wide-project.

**Comment by hahnjo** [comment]
I think this should be a wiki page instead of an issue...

**Comment by agheata** [comment]
It seemed more "cast in stone" there, but sure, I can move it, we can edit the wiki there and it does not need to contain all comments

**Comment by agheata** [comment]
Moved at https://github.com/apt-sim/AdePT/wiki/AdePT#roadmap
