### ISSUE TITLE
Move VariableSizeObj base helper in VecCore

### ISSUE THREAD

**Issue by agheata** [apt-sim/AdePT#14]
As @graeme-a-stewart  was pointing out, core data structures are better placed into core libraries. The VariableSizeObj is one of those, allowing to construct variable size objects adopting memory (quite essential for CUDA), so we should move this from VecGeom to VecCore (which seems to match the original intent of the developers)

**Comment by drbenmorgan** [comment]
Could I also request some additional docs/examples on `VariableSizeObj` please? Its intent/uses on host/device are a still a bit vague to me at the moment.

**Comment by amadio** [comment]
I disagree, VecCore is a library for SIMD support, anything that is not related to SIMD vectorization does not belong there.

**Comment by WitekPokorski** [comment]
Yes, but it does not belong to VecGeom either. Should we create another base library?

**Comment by graeme-a-stewart** [comment]
Bear in mind we do want to support CPU comilation as well, although the primary goal is needed functionalty on the GPU. That said, how VecCore does things may just not be suitable for the GPU (I am not familiar enough with it to really say). 

It may indeed be optimal to start a new support library, oriented to GPUs, rather than carry the VecCore code to places it was never foreseen to go. That's probably a bit more agile.

**Comment by agheata** [comment]
Fair enough, then we need a new (header) library for this. Note that it is probably not a good idea to bind it to apt-sim since it is of larger scope. To be discussed in the meeting.

**Comment by graeme-a-stewart** [comment]
I would create it here in apt-sim first - GitHub makes it realy easy to move or rename repositories later on.

So I guess we need a new name then... 🤔  I'm thinking GPUs, accelerators, data structures (too specific?), utilities and core stuff... 

AccelCore? CopCore? (Co-processor)

**Comment by agheata** [comment]
CopCore +1

**Comment by agheata** [comment]
> Could I also request some additional docs/examples on `VariableSizeObj` please? Its intent/uses on host/device are a still a bit vague to me at the moment.

@drbenmorgan indeed, the usage is not obvious looking at the interfaces. It is supposed to work on both host/device, the idea is to handle adoption of memory for an array of arbitrary size of arbitrary objects. Derived types cannot be allocated with new, but rather with MakeInstance(At)(size_t nobjects). MakeInstance(size_t) calls 'new' inside, so the user contract is to call ReleaseInstance(obj). This is not the case for adopting memory, where the size has to be retrieved using the static method SizeOfInstance() (or SizeOfAligned for an array of VariableSizeObj-derived types). In this case MakeInstanceAt(size_t, void * addr) shouild not be followed by ReleaseInstance, but rather by delete[] (host) or cudaFree(device) for the allocated buffer. 
For composite VariableSizeObj types, the internal size computation ignores the size of the embedded data (in case of memory allocation, not adoption), this is why your simple test crashes. I'm working on a fix in VariableSizeObj for that. Derived types are also copiable. 
I will properly document these when moving into the new library.

**Comment by WitekPokorski** [comment]
CopCore +1

**Comment by drbenmorgan** [comment]
No preference on name, but agree with @graeme-a-stewart to keep it as a sub package here to begin with!

**Comment by WitekPokorski** [comment]
I guess, this is done? Can we close it?
