### ISSUE TITLE
Example14 misses EM processes for muons, hadrons, ions

### ISSUE THREAD

**Issue by hahnjo** [apt-sim/AdePT#178]
In https://github.com/apt-sim/AdePT/blob/85d79b868a458941e39aa852e9fd1fba8ba85fe8/examples/Example14/src/FTFP_BERT_HepEm.cc#L37-L39 we completely disable `G4EmStandardPhysics` and replace it with `PhysListHepEm`, which uses G4HepEm but only for electrons, positrons and gammas. This works fine as long as we stay in the closed domain of those particles, but will lead to problems if we simulate a pion shower, for example. What we're missing is (at least) the equivalent of https://github.com/Geant4/geant4/blob/84f33a068c5e0acb278dc4e4acb6a2822c6e7bca/source/physics_lists/constructors/electromagnetic/src/G4EmStandardPhysics.cc#L222-L233

**Comment by WitekPokorski** [comment]
I have added the missing part in https://github.com/WitekPokorski/AdePT/blob/xtraem/examples/Example14/src/PhysListHepEm.cc
I think, it's OK now, but to be tested. 
Please let me know if you see any side effects.
