### ISSUE TITLE
Move to C++17

### ISSUE THREAD

**Issue by bernhardmgruber** [apt-sim/AdePT#191]
VecGeom moved to C++17, so we should move AdePT as well.

**Comment by bernhardmgruber** [comment]
@amadio you said we should move AdePT to C++17, but judging from the main CMakeLists.txt, that is already enforced? Is this already done?

**Comment by amadio** [comment]
There was an issue in the past where the decision was to stay with C++14 for CUDA code, but at the time CUDA 11 was still too fresh. Right now indeed, the move has already happened and the default in AdePT is to use C++17 for both C++ and CUDA code.
