### ISSUE TITLE
Decide on copyright for code

### ISSUE THREAD

**Issue by graeme-a-stewart** [apt-sim/AdePT#2]
We have a licence (Apache2 👍), but we also need the code to be copyrighted.

My suggestion would be that we (C) to CERN as the "mother lab" for the project. That should be ok for all HEP contributors.

Then all source files should have:

```
// SPDX-FileCopyrightText: 2020 CERN
// SPDX-License-Identifier: Apache-2.0 
```

We should also write a contribution guide and this should be in.

I also found that we can have a GitHub action that would check compliance, see <https://reuse.software/>.

**Comment by drbenmorgan** [comment]
@graeme-a-stewart, I very quickly tried the Reuse workflow on a branch, and works nicely so ready to go when needed.

**Comment by agheata** [comment]
@graeme-a-stewart and @drbenmorgan I agree with copyrighting and Reuse. I added you both to the list of repo admins in case you want to activate it.

**Comment by graeme-a-stewart** [comment]
I just realised (when implementing the Reuse workflow) that Apache-2.0, while a great license for code, isn't the best for documentation. I would then also suggest that we a Creative Commons license for documentation, CC-BY-4.0.
