### ISSUE TITLE
Implement Host/Device etc macros for `AdePT` and/or `CopCore`

### ISSUE THREAD

**Issue by drbenmorgan** [apt-sim/AdePT#24]
Per discussion in meetings and raised on PR #17, we should implement macros for decorating functions/classes/etc with the needed Host/Device keywords and so on.

There'll necessarily be duplication of some features in VecCore/VecGeom, but I don't think this avoidable _for now_. This can be reviewed/refactored in due course once any public/common interfaces solidify a bit more. 

I've assigned myself in the interim, so will link a PR here in due course, but comments, discussion welcome in the meantime!

**Comment by drbenmorgan** [comment]
Ping @agheata, @amadio, @WitekPokorski, @graeme-a-stewart for feedback!

**Comment by graeme-a-stewart** [comment]
HI @drbenmorgan - there is another way to do this, following the Allen model, which I will show tomorrow. In a nutshell, use CUDA keywords, but redefine them as needed for other targets. There are some advantages to this way.

**Comment by amadio** [comment]
It depends if we plan to support something other than CUDA or not. If not, my favorite "abstraction" is to just write CUDA code and define `__host__` and `__device__` to nothing when CUDA is disabled, i.e.
```cpp
#ifndef __NVCC__ // (or __CUDACC__)
#define __host__
#define __device__
#endif
```

**Comment by graeme-a-stewart** [comment]
And that is exactly what the Allen team do 😉

**Comment by drbenmorgan** [comment]
Excellent! Will wait for the Allen feedback tomorrow. The other way is to follow the VecCore/VecGeom way, or the Celeritas (and by extension/reversion) Kokkos:

https://github.com/celeritas-project/celeritas/blob/master/src/base/Macros.hh

There are other aspects like the inline forcing, attributes, visibility etc that we may want to consider (guess a similar approach can work).

**Comment by amadio** [comment]
> There are other aspects like the inline forcing, ...

Reminds me of https://github.com/git/git/blob/master/Makefile#L1313-L1315, which goes in a similar direction as my suggestion above.

**Comment by drbenmorgan** [comment]
Like #26, mark as resolved for now by the `CopCore/Macros.h` header.
