### ISSUE TITLE
Implement Allen-esque device code redefinitions for different devices

### ISSUE THREAD

**Issue by graeme-a-stewart** [apt-sim/AdePT#26]
After [discussing](https://cernbox.cern.ch/index.php/s/PkGgKVdwAOUsUQD) the implementation that the Allen project uses to handle different backend devices we decided that it is a good option for AdePT. In brief:

- CUDA is the "native" language
- Based on the target device, the CUDA keywords and functions are redfined to be appropriate to that backend

We decided to then implent this in AdePT, but in the copcore library.

We shall try to base this on the refactored backend code that Daniel has written:

<https://gitlab.cern.ch/lhcb/Allen/-/tree/dcampora_test_velo_performance/backend>

(Note in passing about the [interesting discussion](https://gitlab.cern.ch/lhcb/Allen/-/merge_requests/414) on this MR)

Closes #24 
Closes #25

**Comment by shefmarkh** [comment]
Hello,

So if I understood what the linked Allen code does it allows to switch between GPU code styles and CPU C++ code with some definitions.

"Based on the target device, the CUDA keywords and functions are redfined to be appropriate to that backend"

Then this would allow one to toggle from CUDA code to <code_for_some_other_device_manufacturer> when e.g not using an nvidia GPU.

So if I understand correctly the Allen code essentially does the same job as Alpaka does (which also has its own way of swapping between CPU/GPU code for CPU and different GPU hardware )?

So then one would not want a way to swap CPU/CUDA/Other_GPU_CODE/Alpaka but rather the OR of (CPU/CUDA/OTHER_GPU_CODE, which is itself an OR) and Alpaka?

Cheers,

Mark

**Comment by graeme-a-stewart** [comment]
Hi Mark - yes, this is the essence of the idea. The motivation is to keep things simple for now, take advantage of all of the good documentation that is out there right now for CUDA programming, but try to support the CPU as well, for debugging. It also allows us to try some advanced CUDA feautres not supprted in generic abstaction libraries, like texture memory and graphs (even though here we might need a separate CPU implementation).

It's a balance between allowing us to develop and prototype fast now, then look later at how we sustain the code in the long term. As things evolve the choice between alpaka, kokkos, oneapi, etc. should also maybe become clearer.

**Comment by drbenmorgan** [comment]
I'm going to close this as essentially resolved by the `CopCore/Macros.h` header where we used "Allen style" re-defs of `__host__` and `__device__` for now.
