### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by graeme-a-stewart** [apt-sim/AdePT#3]
We should add a contribution guide for the project that explains how to help (and that covers everything, from just raising an issue, to fixing documentation all the way to writing super-charged GPU code).

There are a few examples of ones that were done for recent HSF projects:

- prmon: <https://github.com/HSF/prmon/blob/master/doc/CONTRIBUTING.md>
- acts: <https://github.com/acts-project/acts/blob/master/CONTRIBUTING.md>
- phoenix: <https://github.com/HSF/phoenix/blob/master/CONTRIBUTING.md>

**Comment by agheata** [comment]
I like the ACTS contribution guide, maybe we can have a variant of that
