### ISSUE TITLE
Problems using existing cuda10.2 toolkit

### ISSUE THREAD

**Issue by agheata** [apt-sim/AdePT#5]
I'm using cmake 3.18.2 and I have a freshly updated cuda10.2 on my Ubuntu 18.04 machine with a Quadro K4200 (yes, old...) card, the driver works OK and I can compile VecGeom with CUDA. Note that VecGeom uses the old style find_package(CUDA) rather than the new find_package(CUDAToolkit). Trying to compile AdePT, I get from CMake:

-- The CUDA compiler identification is unknown
-- Detecting CUDA compiler ABI info
CMake Error in /home/agheata/geant_src/adept_build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_6bf1b".
CMake Error at /usr/local/share/cmake-3.18/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/CMakeTestCUDACompiler.cmake:19 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:2 (project)

Note that nvcc is found, I even specify -DCUDA_Toolkit_ROOT=/usr/local/cuda-10.2 to cmake
Trying to debug this... any hints appreciated

**Comment by drbenmorgan** [comment]
Hmm, what output do you get prior to the initial `-- The CUDA compiler identification is unknown`? The fundamental issue _I think_ is that as CMake can't identify the compiler, it can't set a default for `CMAKE_CUDA_ARCHITECTURES`.

Just to see if it can get past the `-- Detecting CUDA compiler API info` step, you could try

```
$ cmake -DCMAKE_CUDA_ARCHITECTURES=30 <args>
```

which would be suitable for the toolkit version and card.

**Comment by agheata** [comment]
Thanks, it was in fact due to an old driver installation that left over the nvcc executable in my /usr/bin. Removing it made it compile flawlessly...
