### ISSUE TITLE
Particle and track data structures in AdePT

### ISSUE THREAD

**Issue by amadio** [apt-sim/AdePT#72]
The most fundamental data structure for the whole project is the data structure that holds tracks to be simulated. In this issue, we should discuss which pieces of data will be necessary in this data structure, and decide on an initial in-memory layout for this data as well as on an initial API to access it from both CPU and GPU in a generic way.

In this issue, we should discuss:
 - What components are needed in the track data structure (name, type, size in bytes)
 - In-memory data layouts for CPU and GPU
 - API required to access data on CPU and GPU
 - Memory management of track data
 - Specializations for different particle types if required

Design Goals:
  - Data that is common to all tracks of a given type should not be repeated in memory (i.e. pdg code, or charge/mass for photons).
  - The API to create/delete/access/modify tracks should not expose the in-memory data layout to other parts of the code. This is necessary to allow the data layout to be changed later to optimize for performance, and to allow different layouts on the CPU/GPU if necessary.
  - We should strive to design the data layouts and the API in a way that allows easy modification/extension of the data components for each track. This is important to create a system in which we can have track data that is specialized for different particle types. That is, omit charge and mass for neutral and massless particles, but add polarization, or atomic properties for ions if required. If all tracks must use the exact same data layout, we will waste memory and not be able to fit as many tracks on the device to run in parallel.
  - Dynamic memory management happening at fixed-sized blocks of tracks in between simulation steps. Rationale: memory allocation within a kernel is complex to handle, as a call to `malloc()` from within a kernel will actually allocate memory for every block, which depends on kernel launch configuration. Therefore, it is better to have allocations happen in between kernel calls instead, or inside a specific kernel for this purpose.

Required components:
 - track id, parent track id, event id, geometry id (i.e. navigation state), material id (+region id), position, momentum, energy, global/proper time, RNG state, flags field (dead/alive, active physics process, and other boolean flags).

Optional components:
 - spin, polarization, ionization state, nuclear excitation state, etc

Others:
 - components used during stepping (i.e. cached safety, interaction length, etc), and for scoring (i.e. hit information)

Proposed data layout:

Data layout could be based on entity component systems, which are common to handle many diverse objects in computer games. Each particle type would be an *archetype* in this system, and contain its own set of components. Each stepping phase would be one *behavior* depending on one or more *systems* for physics models, etc. Please see reference below for more information about these concepts.

<p align="center">
<img src="https://user-images.githubusercontent.com/249404/106002194-215aaa80-60b1-11eb-8942-939080d98f35.png" width="50%" /></p>

<p align="center">
<img src="https://user-images.githubusercontent.com/249404/106000510-2d456d00-60af-11eb-9e26-06e3113e2abe.png" width="50%" /></p>

Required functionality:

  - Query if an archetype (e.g. a particle type) has a given component (by name or id number)
  - Query what is the type/size of some component in an archetype
  - Query number of memory chunks, number of entities per memory chunk
  - Query what is the offset (from base pointer to a memory chunk) of some component in an archetype
  - Query and set on/off mask status of an entity slot or full memory chunk
  - Query and set the value of a component of an entity (i.e. query/set position of a given particle)
  - Query number of entities (active slots) and capacity (i.e. including holes)
  - APIs to insert, erase, and swap entities
  - Sorting to remove unused slots in memory chunks
  - Sorting of entities based on mask/bool components
  - Iteration over memory chunks (for CPU) and random access of memory chunks by number (for GPU)

**References**:
 - [PDG Table of Particle Information](https://pdg.lbl.gov/2020/html/computer_read.html)
 - [Geant4 Particles](https://github.com/Geant4/geant4/tree/master/source/particles/management)
 - [ECS Concepts in Unity](https://docs.unity3d.com/Packages/com.unity.entities@0.17/manual/ecs_core.html)
 - [Entity Component Systems & Data Oriented Design](http://aras-p.info/texts/files/2018Academy%20-%20ECS-DoD.pdf)
 - [Design and Implementation of Particle Systems for Meshfree Methods with High Performance](https://www.intechopen.com/books/high-performance-parallel-computing/design-and-implementation-of-particle-systems-for-meshfree-methods-with-high-performance)
 - [Data Oriented Design and C++ (video)](https://www.youtube.com/watch?v=rX0ItVEVjHc)
 - [Data Oriented Design and C++ (slides)](https://github.com/CppCon/CppCon2014/tree/master/Presentations/Data-Oriented%20Design%20and%20C%2B%2B)
 - [`std::colony`](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0447r12.html) proposal and [implementation in PLF library](https://plflib.org/colony.htm) (thanks @bernhardmgruber for the pointers)

**Comment by amadio** [comment]
Here is a [gist](https://gist.github.com/amadio/69c8524af31e50ff2e717ba3137bf005) with a simple example of how to obtain good performance on CPU/GPU by using SoA layout. The next step will be to work on good interfaces that satisfy our requirements as written above and that are able to handle data like this within a larger code that may have different kinds of tracks.

**Comment by hageboeck** [comment]
I played as well, see [here](https://github.com/hageboeck/AdePT/tree/ECS/examples/ECS).

Slides [here](https://indico.cern.ch/event/1006398/).

**Comment by hageboeck** [comment]
Some more results are discussed here:
https://indico.cern.ch/event/1020971/
